### ISSUE TITLE
lucene Error

### ISSUE THREAD

**Issue by fatmas1982** [valeriobasile/learningbyreading#20]
`./run.sh -i ./text/multilingual-all-words.en.xml -o ./out/lesk_wsd_dsm_test -cm doc -f xml -dsm ./resources/dsm/termvectors_en.bin -lang en -sc ./resources/sense/sense.freq -sf bn -c max -of task -depth 1
Run Lesk-wsd-dsm algorithm...
Nov 20, 2018 7:53:57 PM di.uniba.it.exec.RunWSD main
INFO: Init...
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.lucene.store.FSDirectory.open(Ljava/io/File;)Lorg/apache/lucene/store/FSDirectory;
	at di.uniba.it.wsd.dsm.LuceneVectorStore.init(LuceneVectorStore.java:68)
	at di.uniba.it.exec.RunWSD.main(RunWSD.java:144)
`
Could you help me ?

**Comment by fatmas1982** [comment]
This is happened in lesk-wsd-dsm project

**Comment by valeriobasile** [comment]
Issue reported to the repository of the external dependency: https://github.com/pippokill/lesk-wsd-dsm/issues/4
